# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1df5f7ddedcb1688accee7022f7842bc036aa4af37ace4de11f8f54144e00ceee765233d9b11580a4a1b8591847036538ec3e72076442e03efe43766ed9db9e2

test:
  secret_key_base: 1421bc971d3011627648f87e2dac849455ac6c01ab5d3630d60828b79fc11a2481b8a698550ea21964c211f947159d197b808e427e0ca1e998c97c2066104361

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
